## Workflow of Neural Network Pipelines

In [190]:
import numpy as np 
import pandas as pd 
import torch 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split

In [191]:
df=pd.read_csv(r"C:\Users\Pavitra\Downloads\PyTorch\Breast-Cancer_dataset\breast-cancer.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [192]:
df.shape

(569, 32)

In [193]:
df.drop(["id"],inplace=True,axis=1)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [195]:
df.iloc[:,0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

### train_test_split

In [196]:
x_train , x_test, y_train , y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

### scaling

In [197]:
### for x

In [198]:
scaler= StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [199]:
x_train

array([[-0.17135344, -1.92182141, -0.1709511 , ..., -0.64943828,
        -0.32567596, -0.65293385],
       [-0.93000135, -0.82314833, -0.8984055 , ..., -0.5638102 ,
        -0.52518491,  1.2811652 ],
       [-0.65517041, -0.04374776, -0.68640451, ..., -0.72510961,
        -0.59632763, -0.22313406],
       ...,
       [-0.82121411,  0.19570662, -0.7608127 , ..., -0.35732245,
         0.05323638, -0.75046947],
       [-1.27697542, -0.2409455 , -1.287074  , ..., -1.40109659,
         0.21098764, -0.28637144],
       [-1.2257309 , -0.80906277, -1.20643048, ..., -0.78408423,
        -0.64736481,  0.42853245]], shape=(455, 30))

In [200]:
x_test

array([[ 0.67890478, -0.19634125,  0.6059702 , ..., -0.38657999,
        -0.81439555, -1.03986084],
       [-0.30876891, -1.24101971, -0.38710898, ..., -1.24301398,
        -1.25826429, -0.98037484],
       [-0.94717829,  1.19343325, -0.96159011, ..., -1.28406644,
         0.2140808 , -0.41981302],
       ...,
       [ 1.94427224,  1.40002135,  2.11907536, ...,  2.1098079 ,
         0.01302527,  0.78437667],
       [ 0.26665837,  0.16518793,  0.34408662, ...,  1.45572578,
        -0.13389992, -0.09397976],
       [-0.72387815, -0.1799081 , -0.75416169, ..., -0.51448598,
         0.44761452, -0.29280236]], shape=(114, 30))

In [201]:
### for y

In [202]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [203]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

### Converting to Tensors

In [204]:
x_train_ten=torch.from_numpy(x_train)
x_test_ten=torch.from_numpy(x_test)
y_train_ten=torch.from_numpy(y_train)
y_test_ten=torch.from_numpy(y_test)

In [205]:
x_train_ten

tensor([[-0.1714, -1.9218, -0.1710,  ..., -0.6494, -0.3257, -0.6529],
        [-0.9300, -0.8231, -0.8984,  ..., -0.5638, -0.5252,  1.2812],
        [-0.6552, -0.0437, -0.6864,  ..., -0.7251, -0.5963, -0.2231],
        ...,
        [-0.8212,  0.1957, -0.7608,  ..., -0.3573,  0.0532, -0.7505],
        [-1.2770, -0.2409, -1.2871,  ..., -1.4011,  0.2110, -0.2864],
        [-1.2257, -0.8091, -1.2064,  ..., -0.7841, -0.6474,  0.4285]],
       dtype=torch.float64)

In [206]:
y_train_ten.shape

torch.Size([455])

### Defining the model

In [207]:
class MySimpleNN():
    def __init__(self,X):         # defining the archietecture of the NN
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward_pass(self,X):       # Forward pass
        z=torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss_func(self,y_pred,Y):  # Loss calcuation per epoch
        ep=1e-7
        y_pred=torch.clamp(y_pred,ep,1-ep)
        loss= -(Y*torch.log(y_pred) + (1-Y)*torch.log(1-y_pred)).mean()
    
        return loss

    def parameter_update(self):    # Parameter Updation
        loss.backward()

In [208]:
### important parameters

learning_rate=0.1
epochs=25

In [209]:
## creating the model 

model= MySimpleNN(x_train_ten)

In [210]:
model.weights

tensor([[0.4972],
        [0.7225],
        [0.6479],
        [0.1525],
        [0.2102],
        [0.5182],
        [0.3464],
        [0.7022],
        [0.8855],
        [0.3751],
        [0.2271],
        [0.9024],
        [0.1338],
        [0.8276],
        [0.2842],
        [0.2452],
        [0.6204],
        [0.5350],
        [0.1385],
        [0.2131],
        [0.1798],
        [0.3968],
        [0.2709],
        [0.3577],
        [0.4727],
        [0.2722],
        [0.0251],
        [0.8502],
        [0.7593],
        [0.4428]], dtype=torch.float64, requires_grad=True)

In [211]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [212]:
### training the model 

for epoch in range(epochs):

    # forward pass 
    y_pred=model.forward_pass(x_train_ten)
  

    # loss 
    loss=model.loss_func(y_pred,y_train_ten)

    # backward pass
    model.parameter_update()

    # parametr updation
    with torch.no_grad():
        model.weights -= learning_rate * (model.weights.grad)
        model.bias-= learning_rate * (model.bias.grad)

    # zero gradients 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f" for EPOCH {epoch+1} => LOSS = {loss}")

 for EPOCH 1 => LOSS = 3.2622624673740854
 for EPOCH 2 => LOSS = 3.1213890706848906
 for EPOCH 3 => LOSS = 2.974909752190503
 for EPOCH 4 => LOSS = 2.821588519051338
 for EPOCH 5 => LOSS = 2.6622497665495777
 for EPOCH 6 => LOSS = 2.500298476746408
 for EPOCH 7 => LOSS = 2.3353041365521325
 for EPOCH 8 => LOSS = 2.1652024452157512
 for EPOCH 9 => LOSS = 1.996367416738065
 for EPOCH 10 => LOSS = 1.8324066087936073
 for EPOCH 11 => LOSS = 1.6758593527999623
 for EPOCH 12 => LOSS = 1.523586389666511
 for EPOCH 13 => LOSS = 1.3844918286884462
 for EPOCH 14 => LOSS = 1.2604126770762762
 for EPOCH 15 => LOSS = 1.1529180920448732
 for EPOCH 16 => LOSS = 1.0629480820724035
 for EPOCH 17 => LOSS = 0.990401921529881
 for EPOCH 18 => LOSS = 0.9339084329353056
 for EPOCH 19 => LOSS = 0.8910279271305648
 for EPOCH 20 => LOSS = 0.8588462449343117
 for EPOCH 21 => LOSS = 0.8345879545781416
 for EPOCH 22 => LOSS = 0.8159695689770933
 for EPOCH 23 => LOSS = 0.8012878292873623
 for EPOCH 24 => LOSS = 0.7893523392817661
 for EPOCH 25 => LOSS = 0.7793629413055321

In [213]:
model.weights

tensor([[ 0.1335],
        [ 0.3048],
        [ 0.2613],
        [-0.2119],
        [-0.1820],
        [-0.0167],
        [-0.2047],
        [ 0.1562],
        [ 0.3957],
        [ 0.1064],
        [-0.1858],
        [ 0.6073],
        [-0.2764],
        [ 0.4621],
        [ 0.0821],
        [-0.1709],
        [ 0.2599],
        [ 0.0761],
        [-0.1082],
        [-0.1008],
        [-0.2248],
        [-0.0312],
        [-0.1512],
        [-0.0366],
        [ 0.1029],
        [-0.1891],
        [-0.4720],
        [ 0.3141],
        [ 0.3707],
        [ 0.0743]], dtype=torch.float64, requires_grad=True)

In [217]:
with torch.no_grad():
    y_pred=model.forward_pass(x_test_ten)
    y_pred=(y_pred>0.5).float()
    print(y_pred,y_test_ten)
    
    accuracy=(y_pred == y_test_ten).float().mean()
    
    print(f"Accuracy : {accuracy}")

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]) tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0])
Accuracy : 0.5323176383972168